# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Microservice
  licenses: {! cookiecutter.license !}
  images: |
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r33
    - name: {! cookiecutter.image_name !}
      image: docker.io/{! cookiecutter.__organization_name !}/{! cookiecutter.image_name !}:{! cookiecutter.image_tag !}
apiVersion: v2
appVersion: {! cookiecutter.app_version !}
dependencies:
{% if cookiecutter.use_db == 'postgresql' -%}
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
{% elif cookiecutter.use_db == 'mariadb' -%}
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
{% elif cookiecutter.use_db == 'mysql' -%}
- condition: mysql.enabled
  name: mysql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
{% endif -%}
{% if cookiecutter.use_cache -%}
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
{% endif -%}
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: {! cookiecutter.chart_description !}
home: https://laragis.vn
icon: https://laragis.vn/assets/stacks/{! cookiecutter.image_name !}/img/{! cookiecutter.image_name !}-stack-220x234.png
keywords:
- application
- http
- web
maintainers:
- name: {! cookiecutter.author_name !}.
  url: https://github.com/{! cookiecutter.__organization_name !}/charts
name: {! cookiecutter.chart_name !}
sources:
- https://github.com/{! cookiecutter.__organization_name !}/charts/tree/main/{! cookiecutter.__organization_name !}/{! cookiecutter.chart_name !}
- https://github.com/{! cookiecutter.__organization_name !}/containers/tree/main/{! cookiecutter.__organization_name !}/{! cookiecutter.image_name !}
version: {! cookiecutter.chart_version !}
